### PR TITLE
Fix used wrong config in ConfigDialog.cpp

### LINKED ISSUE #378: Git Repo settings are not saved on Flatpack kubuntu
On every program run there are no git repos anymore.

### PR DESCRIPTION
**Pull request by Murmele**
Fix used wrong config in ConfigDialog.cpp the readconfig and the write config must be the same

Changed part is in ConfigDialog.cpp

fixes #378

### CODE REVIEW

File: src/dialogs/ConfigDialog.cpp [hunk 1]
```diff
@@ -100,46 +100,46 @@ class GeneralPanel : public QWidget {
...
 
     connect(mPullUpdate, &QCheckBox::toggled, this, [this](bool checked) {
-      git::Config config = mRepo.config();
+      git::Config config = mRepo.appConfig();
       config.setValue("autoupdate.enable", checked);
     });
 
     connect(mAutoPrune, &QCheckBox::toggled, this, [this](bool checked) {
-      git::Config config = mRepo.config();
+      git::Config config = mRepo.appConfig();
```
Comment (Murmele) [inline src/dialogs/ConfigDialog.cpp:136]: those lines

**Review by exactly-one-kas — APPROVED** [review]
