### PR TITLE
Fix AUR builds

### LINKED ISSUE #217: AUR Build Error
First i tried installing it using `paru -S gittyup` then `paru -S gittyup-git` and last with `git clone git clone https://aur.archlinux.org/gittyup.git` & `makepkg -si`
Always the Same error. 
Do you have an Idea how this could happen?

```
[***@*******-arch ~]$ gittyup
Theme dir:  QDir( "/home/***/packages/github/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Theme dir:  QDir( "/home/***/packages/github/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
PANIC: unprotected error in call to Lua API (cannot open /home/***/packages/github/gittyup/src/build/Resources/System.lua: No such file or directory)
Aborted (core dumped)
[***@*****01-arch ~]$
```

### PR DESCRIPTION
**Pull request by exactly-one-kas**
TODO:
- [x] Replace my repository URL in PKGBUILD with proper URL when approved

This overhauls quite a lot:
- Fix tests to work on machines without GIT configured
- Disable tests that touch global configuration by default
- Remove empty HunkWidget test
- Make resource install directory configurable
- Copy resources into output directory so that debugging works
- Replace "OK" button with "Remind me later" and "Skip this version" for non-updateable builds
- Allow using system-wide installations of most dependencies
- Make debug output suppressable and disable it in CI builds

@Murmele this is built upon your branch `ArchBuild`, but I rebased it onto the current `master`
@alerque Does this work for you?

Fixes #217 and #20
Relates to #191 and #16

### CODE REVIEW

**Comment by Murmele** [comment]
@exactly-one-kas shall we have the PKGBUILD in this repository? I did not understand yet how to push to the AUR git repository but I think we should place it there?

**Comment by Murmele** [comment]
There are some proposals for the PKGBUILD. I have to test them next days to see what is needed.
https://aur.archlinux.org/packages/gittyup#comment-872036

**Comment by exactly-one-kas** [comment]
> I did not understand yet how to push to the AUR git repository but I think we should place it there?

Currently, `gittyup` is maintained by @alerque, `gittyup-git` is maintained by @FabioLolix
We don't have to (or can) push anything

@FabioLolix sorry for only brining you into this now, I overlooked your package ( ._.)
Do these changes work for you as well?

File: pack/PKGBUILD [hunk 1]
```diff
@@ -6,55 +6,89 @@
...
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_PREFIX_PATH=/usr \
+    -DDEBUG_OUTPUT=OFF \
+    -DUSE_SYSTEM_OPENSSL=ON \
+    -DUSE_SYSTEM_LIBSSH2=ON \
+    -DUSE_SYSTEM_GIT=ON \
+    -DUSE_SYSTEM_LUA=ON \
+    -DUSE_SYSTEM_HUNSPELL=ON \
+    -DUSE_SYSTEM_CMARK=ON \
+    -DLUA_MODULES_PATH=/usr/lib/lua/5.4 \
```
Comment (Murmele) [inline pack/PKGBUILD:50]: the version here? Can we parse the version somehow from `lua -v`?

File: src/update/UpdateDialog.cpp [hunk 2]
```diff
@@ -94,6 +94,8 @@ UpdateDialog::UpdateDialog(const QString &platform, const QString &version,
   QDialogButtonBox *buttons = new QDialogButtonBox(this);
 #if !defined(Q_OS_LINUX) || defined(FLATPAK) || defined(DEBUG_FLATPAK)
   buttons->addButton(tr("Install Update"), QDialogButtonBox::AcceptRole);
+#endif
+
```
Comment (Murmele) [inline src/update/UpdateDialog.cpp:98]: Skip makes sense if on ubuntu a newer version will be served at a later point the application does not ask every time when opening.
But the remind me later button?

**Comment by Murmele** [comment]
Flatpak is not working yet 
```
flatpak run com.github.Murmele.Gittyup                         
Gtk-Message: 13:30:03.518: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:30:03.545: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:30:03.545: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Theme dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Theme dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
PANIC: unprotected error in call to Lua API (cannot open /app/share/gittyup/Resources/System.lua: Datei oder Verzeichnis nicht gefunden)
```

**Comment by Murmele** [comment]
> Flatpak is not working yet
> 
> ```
> flatpak run com.github.Murmele.Gittyup                         
> Gtk-Message: 13:30:03.518: Failed to load module "xapp-gtk3-module"
> Gtk-Message: 13:30:03.545: Failed to load module "canberra-gtk-module"
> Gtk-Message: 13:30:03.545: Failed to load module "canberra-gtk-module"
> Qt: Session management error: None of the authentication protocols specified are supported
> Theme dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
> Theme dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
> PANIC: unprotected error in call to Lua API (cannot open /app/share/gittyup/Resources/System.lua: Datei oder Verzeichnis nicht gefunden)
> ```

The System.lua is now in Resources/themes not directly in Resources

**Comment by Murmele** [comment]
> > Flatpak is not working yet
> > ```
> > flatpak run com.github.Murmele.Gittyup                         
> > Gtk-Message: 13:30:03.518: Failed to load module "xapp-gtk3-module"
> > Gtk-Message: 13:30:03.545: Failed to load module "canberra-gtk-module"
> > Gtk-Message: 13:30:03.545: Failed to load module "canberra-gtk-module"
> > Qt: Session management error: None of the authentication protocols specified are supported
> > Theme dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
> > Theme dir:  QDir( "/app/share/gittyup/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
> > PANIC: unprotected error in call to Lua API (cannot open /app/share/gittyup/Resources/System.lua: Datei oder Verzeichnis nicht gefunden)
> > ```
> 
> The System.lua is now in Resources/themes not directly in Resources ThemeDif is still set to Resources
> 
> image

```
if(UNIX)
  target_compile_definitions(
    conf
    PRIVATE CONF_DIR="${CMAKE_INSTALL_FULL_DATADIR}/gittyup/Resources"
            L10N_DIR="${CMAKE_INSTALL_FULL_DATADIR}/gittyup/Resources/l10n")
else()

  target_compile_definitions(conf PRIVATE CONF_DIR="" L10N_DIR="")
endif()
```

File: pack/PKGBUILD (hunk 1 above)
Comment (exactly-one-kas) [reply pack/PKGBUILD:50]: We could, but since this is specifically for Arch, I hardcoded the version from the package repositories (which is also listed as a  dependency)

**Comment by exactly-one-kas** [comment]
> How will be the workflow at the end? I think we should not add the pkgbuild to the repository because then it is again at two places, one in the AUR git repo and one here. Would prefer a way as we have it for flatpak.

That's the idea, but since I made changes to the build system and the file already existed, I used that

> Flatpak is not working yet

It worked in my pristine™ Arch VM with Xorg, but I also have pretty much no experience with Flatpak

File: src/update/UpdateDialog.cpp (hunk 2 above)
Comment (exactly-one-kas) [reply src/update/UpdateDialog.cpp:98]: The skip button suppresses update notifications for the new version indefinitely, while remind me later only dismisses it until the App quits.

**Comment by Murmele** [comment]
image

Do you know if something like this is working?

**Comment by Murmele** [comment]
I pushed the changes so you can have a look into

File: src/update/UpdateDialog.cpp (hunk 2 above)
Comment (Murmele) [reply src/update/UpdateDialog.cpp:98]: ok yes we don't have no OK buttons previously it was by clicking on the x or?

**Comment by Murmele** [comment]
> > Do you know if something like this is working? I did not find any documentation about this PLATFORM_ID
> 
> Here's the documentation: https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html That scheme could work, but I think it would be better if you did the following:
> 
> ```cmake
> if (APPLE OR UNIX)
>     set(RESOURCES_PREFIX ${CONTENTS_DIR}/)
> endif()
> 
> 
> foreach(QM_FILE ${QM_FILES} ${QT_QM_FILES})
>   if(EXISTS ${QM_FILE})
>     install(
>       FILES ${QM_FILE}
>       DESTINATION ${RESOURCES_PREFIX}Resources/l10n
>       COMPONENT ${GITTYUP_NAME})
>   endif()
> endforeach()
> ```

good idea! Flatpak is also running again

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
> > How will be the workflow at the end? I think we should not add the pkgbuild to the repository because then it is again at two places, one in the AUR git repo and one here. Would prefer a way as we have it for flatpak.
> 
> That's the idea, but since I made changes to the build system and the file already existed, I used that
> 
> > Flatpak is not working yet
> 
> It worked in my pristine™ Arch VM with Xorg, but I also have pretty much no experience with Flatpak

Maybe when the MR is ready we can remove the file and add it here until the arch maintainer will pick it up?

**Comment by Murmele** [comment]
e17d08f3392747123debbd7be6c4bb527f8bfbb6 Tested on:
- [x] Archlinux

**Comment by Murmele** [comment]
[PKGBUILD](https://github.com/Murmele/Gittyup/files/9839068/PKGBUILD.txt)

I deleted the file from the repository

**Comment by Murmele** [comment]
Friend tested on mac, it works fein 😄

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
@exactly-one-kas from my side it looks good!

File: pack/PKGBUILD (hunk 1 above)
Comment (Murmele) [reply pack/PKGBUILD]: Ok thanks

**Comment by alerque** [comment]
Hey, sorry I've been traveling and knowing this build was problematic left checking in on it until I was back an regular machines. I'll have a look now and see where we are at!

**Comment by alerque** [comment]
I've had a pull at making a `PKGBUILD` that builds this PR using as many Arch packaging norms as possible. I used the recently deleted one in this PR for some tips about what changed, but also made a number of improvements and changes (adding missing deps, using sources instead of submodules for the remaining external sources, not running the in the prepare step, getting everything working in a chroot, using `ninja install` instead of `ninja package`, etc.).

I can say that the changes in the PR seem to be a huge step in the right direction. Having flags for using system packages for many of the external dependencies is great.

There are still a few more to go, but I don't see any reason not to merge this progress and keep working on the extra bits we need from here.

**Review by alerque — APPROVED** [review]
