### PR TITLE
Fix doc path in Settings

### LINKED ISSUE #351: Fix default docDir to "docs" instead of "doc"
docDir was moved from "doc" to "docs"
See 26d3cfb401f9aaaa341bc240e6390eff1c6c92e2

```
---
 src/conf/Settings.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/conf/Settings.cpp b/src/conf/Settings.cpp
index 0da0f74..50a68a4 100644
--- a/src/conf/Settings.cpp
+++ b/src/conf/Settings.cpp
@@ -241,7 +241,7 @@ QDir Settings::appDir() {
 
 QDir Settings::docDir() {
   QDir dir = rootDir();
-  if (!dir.cd("doc"))
+  if (!dir.cd("docs"))
     dir = confDir();
   return dir;
 }
-- 
```

### PR DESCRIPTION
**Pull request by Murmele**
the doc files are copied into the "Resources" folder in the install path, so use for the docDir() directly the confDir()
As explained in #351 this does not have any impact on the application, because the "doc" / "docs" folder never exists in the install path.

fixes #351

### CODE REVIEW

File: src/conf/Settings.cpp [hunk 1]
```diff
@@ -239,12 +239,7 @@ QDir Settings::appDir() {
   return dir;
 }
 
-QDir Settings::docDir() {
-  QDir dir = rootDir();
-  if (!dir.cd("doc"))
-    dir = confDir();
-  return dir;
-}
+QDir Settings::docDir() { return confDir(); }
```
Comment (exactly-one-kas) [inline src/conf/Settings.cpp:242]: Could we simply remove `docDir()` and replace all calls with `confDir()`?

**Review by exactly-one-kas — APPROVED** [review]
